// Pure helpers shared by check-artifact.mjs (reads out/) and deploy/smoke.mjs (reads the live site):
// the same rules judge the file on disk and the response served by CloudFront.
// Regex-based on purpose: the pages are machine-generated by Next.js, and a DOM dependency is not worth it.

const ENTITIES = { "&amp;": "&", "&quot;": '"', "&#x27;": "'", "&#39;": "'", "&lt;": "<", "&gt;": ">" };

export function decodeEntities(value) {
  return value.replace(/&(?:amp|quot|lt|gt|#x27|#39);/g, (m) => ENTITIES[m]);
}

/** Value of an attribute inside a raw tag body, whatever the attribute order. Handles "..." and '...'. */
function attr(tagBody, name) {
  const match = new RegExp(`(?:^|\\s)${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)')`, "i").exec(tagBody);
  if (!match) return undefined;
  return decodeEntities(match[1] ?? match[2]);
}

/** Contents of every `<meta name="X" content="...">`. Empty array when absent. */
export function metaContents(html, name) {
  const values = [];
  for (const [, body] of html.matchAll(/<meta\b([^>]*)>/gi)) {
    if (attr(body, "name")?.toLowerCase() === name.toLowerCase()) values.push(attr(body, "content") ?? "");
  }
  return values;
}

/** hrefs of the anchors whose visible text (tags stripped) contains `text`, case-insensitive. */
export function anchorHrefsByText(html, text) {
  const hrefs = [];
  for (const [, body, inner] of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    const visible = decodeEntities(inner.replace(/<[^>]*>/g, ""));
    if (visible.toLowerCase().includes(text.toLowerCase())) {
      const href = attr(body, "href");
      if (href !== undefined) hrefs.push(href);
    }
  }
  return hrefs;
}

/** Groups of a robots.txt as `{ agents, rules: [[directive, value]] }`, plus the sitemap lines. */
export function parseRobots(text) {
  const groups = [];
  const sitemaps = [];
  let current = null;
  let lastWasAgent = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, "").trim();
    if (!line) continue;
    const idx = line.indexOf(":");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim().toLowerCase();
    const value = line.slice(idx + 1).trim();
    if (key === "sitemap") {
      sitemaps.push(value);
    } else if (key === "user-agent") {
      if (!current || !lastWasAgent) {
        current = { agents: [], rules: [] };
        groups.push(current);
      }
      current.agents.push(value.toLowerCase());
      lastWasAgent = true;
      continue;
    } else if (current) {
      current.rules.push([key, value]);
    }
    lastWasAgent = false;
  }
  return { groups, sitemaps };
}

/** True when the `*` group blocks everything (`Disallow: /`) and allows nothing. */
export function robotsDisallowsAll(text) {
  const star = parseRobots(text).groups.filter((g) => g.agents.includes("*"));
  const rules = star.flatMap((g) => g.rules);
  return (
    rules.some(([k, v]) => k === "disallow" && v === "/") &&
    !rules.some(([k, v]) => k === "allow" && v !== "")
  );
}

const blocksIndexing = (content) => /(^|[\s,])(noindex|none)([\s,]|$)/i.test(content);
const blocksFollowing = (content) => /(^|[\s,])(nofollow|none)([\s,]|$)/i.test(content);

/**
 * Profile coherence of a page + robots.txt (ADR-004). Returns problems (empty = coherent).
 * staging: noindex+nofollow meta and a robots.txt that disallows all; production: neither.
 * `releaseId`, when given, must equal the m3tric:release meta.
 */
export function profileProblems({ profile, html, robotsTxt, releaseId }) {
  const problems = [];
  const robotsMeta = metaContents(html, "robots");
  if (profile === "staging") {
    if (!robotsMeta.some(blocksIndexing) || !robotsMeta.some(blocksFollowing))
      problems.push(`staging: falta meta robots noindex+nofollow / missing (found: ${JSON.stringify(robotsMeta)})`);
    if (!robotsDisallowsAll(robotsTxt)) problems.push("staging: robots.txt debe tener Disallow: / / must disallow all");
    if (parseRobots(robotsTxt).sitemaps.length > 0) problems.push("staging: robots.txt no debe anunciar sitemap / must not advertise a sitemap");
  } else if (profile === "production") {
    if (robotsMeta.some(blocksIndexing) || robotsMeta.some(blocksFollowing))
      problems.push(`production: meta robots bloquea la indexación / blocks indexing (${JSON.stringify(robotsMeta)})`);
    if (parseRobots(robotsTxt).groups.flatMap((g) => g.rules).some(([k, v]) => k === "disallow" && v === "/"))
      problems.push("production: robots.txt contiene Disallow: / / must not disallow all");
    if (parseRobots(robotsTxt).sitemaps.length === 0) problems.push("production: robots.txt sin Sitemap / missing Sitemap");
  } else {
    problems.push(`perfil desconocido / unknown profile: "${profile}"`);
  }
  if (releaseId) {
    const found = metaContents(html, "m3tric:release");
    if (found.length !== 1 || found[0] !== releaseId)
      problems.push(`meta m3tric:release esperado / expected "${releaseId}", found ${JSON.stringify(found)}`);
  }
  return problems;
}
